apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-secret
  namespace: default
spec:
  encryptedData:
    password: AgCSlxNFy2Nedy2qWWjIRdBdWhGTZF0zm6hdQQseyD5F04nn4lz+VCb4+PPF+gJRHLdSXDVW0YuS1fvpUicsGVAgIPlfmdCGXbf+8gtRShlBSbgBVZh/eAWpWcdUEVs8H9P4YItu92d8EFdEh3i1C/urfZd+5DLMYcaEF4NgUuLWFpK7qCVKdPLCmVzrV7D0F4jWMn7b2Usi9UzVaqzjVyJPubnTsLKryFd3cal1fR1aDlgHDqIfs8k/8cwYYELYJ5R+PrzeuEaWVeSYudVM5Ek4fLl7D9C9u1HuSSd6Sc9dx33egn8y9gvcdUkcAZAk6cdW6fvGqbO6qQWarMY26EqBN8FNTA8P6yVyllogFBpzjTrEkpoK/Jm1jcnB7iyT5PuKP5l5SPOsTULyra6QqNLcANmbEvX1cVoaGui0mmBZQKDvY+U6QLY3G7GiFo53qbPocOH/JcLhrM4kUQlFC7D0mNduXqXiA+vs+oce8JAV8qQnaotdivUMXgjxdboGkk1EVnJuW2/yejrpITJ+3Ulei6x26aQofVMVnVAJnhI/zW+rc5OEjczxgOTx+CzSuUPTomu6bG+D99uV7PJJ0RRUOvAFpKQpj+fCBJhke/G1cBCb8e16XiioXVEwZ7C+Fg8Vcf8zy2xNrNi4Q/mOq/WR+4DXH6E1RhDOa+n1mfUsUhhf5sO6TBkHxHRMQaoSnrM27fgEMNo=
  template:
    metadata:
      creationTimestamp: null
      name: test-secret
      namespace: default
    type: Opaque

